frontend:
  replicaCount: 2
  namespace: grade-submission
  image:
    name: studentgrade.azurecr.io/frontend/frontend
    tag: v1
  service:
    type: ClusterIP
    port: 80
backend:
  replicaCount: 2
  namespace: grade-submission
  image:
    name: studentgrade.azurecr.io/backend/backend
    tag: v1
  service:
    type: ClusterIP
    port: 5000
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  Utilization: 50
postgres:
   hostname: "studentgrade.postgres.database.azure.com"
   database: postgres
ingress:
  enabled: true
  className: nginx
  path: /
workloadidentity:
   id: '6b2208e7-0229-48de-aa02-66d5c1b59e4b'
keyvault:
  enabled: true
  Name: 'seceret-aks123'
imagePullSecrets:
  RegistryName: acr-secret
  data: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJ2aWpheSIsInBhc3N3b3JkIjoiU2FyYW55YUAzMzIyMTEiLCJhdXRoIjoiZG1scVlYazZVMkZ5WVc1NVlVQXpNekl5TVRFPSJ9fX0=
  
#echo -n '{"auths":{"https://index.docker.io/v1/":{"username":"YOUR_DOCKER_USERNAME","password":"YOUR_DOCKER_PASSWORD","email":"YOUR_EMAIL@example.com","auth":"'$(echo -n "YOUR_DOCKER_USERNAME:YOUR_DOCKER_PASSWORD" | base64)'"}}}' | base64 | tr -d '\n'
#secret:
  #DB_USER: 'dmlqYXk='
  #DB_PASS: "U2FyYW55YUAzMzIyMTE="
