apiVersion: v1
kind: Secret
metadata:
  name: acr-secret
  namespace: {{ .Values.backend.namepsace}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{{ .Values.imagePullSecrets.data }}"
