apiVersion: v1 
kind: ServiceAccount
metadata:
  name: student-api-sa
  namespace: {{ .Values.backend.namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.workloadidentity.id }}
