apiVersion: v1
kind: Service
metadata:
  name: studentgrade-api-service
  namespace: {{ .Values.backend.namespace }}
  labels:
    app.kubernetes.io/instance: student-grade-api
spec:
  selector:
    app.kubernetes.io/instance: student-grade-api
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: {{ .Values.backend.service.port }}
