apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.frontend.namespace }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/instance: student-grade-ui
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: {{ .Values.frontend.service.port }}
